import Head from 'next/head'
import { Inter } from 'next/font/google'
import { Layout } from '@/components/Layout'
import Image from 'next/image'
import profilepic from '../../public/images/profile/dev1.png'
import { AnimatedText } from '@/components/AnimatedText'
import Link from 'next/link'
import { LinkArrow } from '@/components/Icons'
import HireMe from '@/components/HireMe'
import lightBulb from '../../public/images/svgs/bulb.svg'
import TransitionEffect from '@/components/TransitionEffect'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>FEECON</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect />
      <main className="flex items-center text-dark w-full min-h-screen dark:text-light ">
        <Layout className="pt-0 md:pt-16 sm:pt-8">
          <div className="flex items-center justify-between w-full lg:flex-col">
            <div className="w-1/2 md:w-full">
              <Image
                src={profilepic}
                alt="FME"
                className="w-full h-auto lg:hidden md:inline-block md:w-full"
                priority
                sizes="(max-widthL768px) 100vw,
                (max-width:1200px) 60vw,
                50vw"
              />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center">
              <AnimatedText
                text="Bringing Dreams to Life: Where Vision Meets Code and Design"
                className="!text-6xl !text-left xl:!text-5xl lg:!text-center  lg:!text-6xl md:!text-6xl sm:!text-3xl"
              />
              <p className="my-4 text-base font-medium md:text-sm sm:text-xs">
                With over 4 years of experience in software engineering, I
                cultivated strong expertise in multiple web based technologies
                in different industries in healthcare and insurance domains. I
                have extensive experience from building software to make them
                production ready. I worked on multiple projects from scratch to
                production. Along with the traditional web development I have
                also pitched in to Saas based technologies like Salesforce, and
                guidewire and understood their basic to advanced implementations
                in some of the previous projects. I am passionate about building
                software that is scalable, maintainable and user friendly. I am
                always eager to learn new technologies and work on challenging
                projects. I am a team player and always ready to help my team
              </p>
              <div className="flex items-center self-start mt-2 lg:self-center">
                <Link
                  href="../../public/resume.pdf"
                  target={"_blank"}
                  className="flex items-center bg-dark text-light p-2 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid hover:border-dark dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light md:p-2 md:px-4 md:text-base "
                  download={true}
                >
                  Resume <LinkArrow className={"w-5 ml-1"} />
                </Link>

                <Link
                  href="contactus"
                  className="ml-4 text-lg font-medium  capitalize text-dark underline dark:text-light md:text-base"
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
          <HireMe />
          <div className="absolute right-8 bottom-0 inline-block w-24">
            <Image
              src={lightBulb}
              alt="Feecon"
              className="w-full h-auto md:hidden"
            />
          </div>
        </Layout>
      </main>
    </>
  );
}
